### ISSUE TITLE
这个在你那里能跑么

### ISSUE THREAD

**Issue by hibichann** [BiologyHazard/Genshin-Skip-Conversation#1]
我这里压根不干活啊，切走就不行了，不切走按p也没反应

**Comment by BiologyHazard** [comment]
我电脑上是能用的，

脚本会检测当前活动窗口的标题是否是“原神”、“崩坏：星穹铁道”，
若是，则在按p键的时候会播放一个声音，您能听到声音吗

**Comment by hibichann** [comment]
> 我电脑上是能用的，
> 
> 脚本会检测当前活动窗口的标题是否是“原神”、“崩坏：星穹铁道”， 若是，则在按p键的时候会播放一个声音，您能听到声音吗

没有，我一切窗口它就不动了，出了窗口去打印key也打印不出来，打印window title也不行
win11
在窗口内按p也打印不出来enable/disable

**Comment by BiologyHazard** [comment]
同样win11，听您的描述可能是按键监听器不工作，但是我没有遇到这样的问题emmm

**Comment by hibichann** [comment]
![{PBCUA~MXOYMOMWOBNN 7T](https://github.com/BiologyHazard/Genshin-Skip-Conversation/assets/17671678/c1fad61e-f466-4eae-a67a-0398458a9dc2)
这样就只有监听在干活，鼠标不会移动，也不会点击，切到其他窗口按键无反应

**Comment by BiologyHazard** [comment]
是啊，你在vscode窗口里面按p，
`while True`死循环里面`if window.title in supported_titles`判断为`False`，自然不会执行移动鼠标和点击操作

**Comment by hibichann** [comment]
不行，都取消了也不行，只会在这个窗口里，要管理员权限？

**Comment by BiologyHazard** [comment]
可以试试管理员权限打开cmd/powershell，通过命令行运行`python skip_conversation.py`

**Comment by hibichann** [comment]
确实是得管理员，

**Comment by BiologyHazard** [comment]
这样能解决是吗

**Comment by hibichann** [comment]
嗯，开管理员

**Comment by hibichann** [comment]
https://github.com/SteveKiller/ApexFarming/blob/main/ApexFarmer.py
以前用过这个是不用管理员的，同一类脚本
